

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/style.css">
    <title>Blog</title>
</head>
<body>
    <header>
        <div class="header">
            <h1>Blog</h1>
            <nav>
                <ul>
                    <li><a href="/<?=$crypt->datacrypt('home-controller')?>~<?=$crypt->datacrypt('viewHome')?>">Accueil</a></li>
                    <li><a href="/<?=$crypt->datacrypt('home-controller')?>~<?=$crypt->datacrypt('viewArticles')?>">Nos articles</a></li>
                    <li><a href="/">Nous contactez</a></li>
                    <li><a href="/">A propos</a></li>
                </ul>
            </nav>
            <a href="/">Se connecter</a>
        </div>
    </header>

    <main>
        <section>
            <h2>Blog Articles</h2>
            <img src="" alt="">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis temporibus nulla rerum ab esse dolorem?</p>
            <input type="text" id="text">
            <button id="valider">Valider</button>
        </section>
        <!-- <section>
            <h2>Nos catégories d'articles</h2>
            <ul>
                <li><a href="">Dépannage</a></li>
                <li><a href="">Dépannage</a></li>
                <li><a href="">Dépannage</a></li>
            </ul>
        </section> -->
        <!-- <section></section> -->
    </main>

    <footer>
        
    </footer>
    <script>
        document.querySelector('#valider').addEventListener("click", () => {
            fetch("/[c9fu1geqtXTszR0gTwxPrWOajaxDGZnqKYv1WuKQz979E0c]/home-controller~viewArticle").then(response => response.json()).then(response  => {
                document.querySelector("#text").value = response;
            });
        })
    </script>
</body>
</html>